### ISSUE TITLE
Jitpack hosting of package renders 404

### ISSUE THREAD

**Issue by StefanWallin** [kantarsifo/SifoInternetAndroidSDK#2]
Requesting library from https://jitpack.io/com/github/kantarsifo/SifoInternetAndroidSDK/3.0.4/SifoInternetAndroidSDK-3.0.4.jar renders a 404 response. Is this intentional?

**Comment by robert-gavelin** [comment]
> Requesting library from https://jitpack.io/com/github/kantarsifo/SifoInternetAndroidSDK/3.0.4/SifoInternetAndroidSDK-3.0.4.jar renders a 404 response. Is this intentional?

Hi @StefanWallin, we have released the new version 3.0.5 that should work better with the latest jitpack version. 

Please verify that it works with: 
`implementation​ ​'com.github.kantarsifo:SifoInternetAndroidSDK:3.X.X'`

**Comment by Swirastlynn** [comment]
We had a problem with
`implementation "com.github.kantarsifo:SifoInternetAndroidSDK:3.0.4"`
but works ok for:
`implementation "com.github.kantarsifo:SifoInternetAndroidSDK:3.0.4@aar"`
should be the same for `3.0.5`
